import "./globals.css";
import Navbar from "./components/navbar/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="container">
          <div className='wrapper'>
             <Navbar />
              {children}
          </div>
        </div>
      </body>
    </html>
  );
}
